### ISSUE TITLE
Issue with Google search

### ISSUE THREAD

**Issue by xiibo** [ganigeorgiev/hide-ratings-extension#5]
Currently the extension doesn't seem to be working correctly, as it even is blocking amazon reviews and reviews from other websites on google search.

**Comment by ganigeorgiev** [comment]
Thanks for the report.

The blurring of all rating elements on google search is intentional and was introduced recently because the source of the ratings cannot always be identified easily.

_You still should be able to reveal the blurred ratings by hovering on them._

**Comment by ganigeorgiev** [comment]
On second thought, maybe it would be better to add a toggle "Blur all google's rating" so that users can on/off it globally.

**Comment by ganigeorgiev** [comment]
New "Blur Google Search ratings" options was added in v1.8.0 release.

_To update the extension, go to `chrome://extensions` and click "Update"._
