### ISSUE TITLE
See the ratings of movies you already rated in letterboxd 

### ISSUE THREAD

**Issue by igorlima1701** [ganigeorgiev/hide-ratings-extension#7]
I think it would be really nice if after we rate a specific movie in letterboxd we could see the rating other people gave on that film. 
Thank you for this awesome plug in!

**Comment by ganigeorgiev** [comment]
Unfortunately this cannot be done with only css and will require running some hacky js solution that may not even work properly on dynamic/ajax loaded content.

_For future versions of the extension, I plan to add the rating toggle as a floating element somewhere inside the related page and that I guess will make turning on/off the ratings a little more convenient._

**Comment by igorlima1701** [comment]
I see. Thank you for the response! 

I'll be expecting this toggle feature. Thank you!
